/*
* 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <iostream>

int main()
{
 
    int sum = 0;
    int temp;
    int arr[3]{1,1,0};

    for (int i = 1; i < i+1; i++)
    {
        //Works out number to be in 3rd place
        arr[2] = arr[0] + arr[1];
        
        //Places 2nd number into the 1st place
        temp = arr[1];
        arr[0] = temp;
        
        //Places 3rd number into 2nd
        arr[1] = arr[2];

        if (arr[2] > 4000000)
            break;

        if (arr[2] % 2 == 0)
        {
            sum += arr[2];
        }
    }
    std::cout << sum;
}
